services:
  database:
    image: postgres:14.5-alpine3.16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=local_database
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: