services:
  database:
        # Docker Hub image
    image: postgres
    environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

  app:
    environment:
      DEBUG: ${{ secrets.DEBUG }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_URL: 'postgres://postgres:postgres@127.0.0.1:5432/postgres'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8000:8000
